# basic options
title: rrtUK devlog
author: red bullion
email: r3d[AT]redbullion.com
description: daily log for rrtUK
twitter_username: tbd
github_username:  rrtUK

# Build settings
markdown: kramdown
theme: minima
